
logging:
  level:
    .: error
    org.springframework: ERROR
    com.mkyong: ERROR

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

server:
  email: default@mkyong.com

---
resilience4j.circuitbreaker:
  configs:
    default:
      register-health-indicator: true
      sliding-window-size: 10
      sliding-window-type: COUNT_BASED
      minimum-number-of-calls: 5
      writable-stack-trace-enabled: true     
      permitted-number-of-calls-in-half-open-state: 2
      automatic-transition-from-open-to-half-open-enabled: true
      wait-duration-in-open-state: 10s
      failure-rate-threshold: 50
  instances:
    backendA:
      baseConfig: default

    backendB:
      register-health-indicator: true
      sliding-window-size: 10
      sliding-window-type: COUNT_BASED
      minimum-number-of-calls: 5
      writable-stack-trace-enabled: true     
      permitted-number-of-calls-in-half-open-state: 2
      automatic-transition-from-open-to-half-open-enabled: true
      wait-duration-in-open-state: 10s
      failure-rate-threshold: 50

spring:
  profiles: dev
  cloud:
    gateway:
      routes:
      - id: order_route
        uri: http://localhost:8084/
        predicates:
        - Path=/order/**
        filters:
          name: CircuitBreaker
          args:
            name: backendA
            fallbackUri: 'forward:/fallback'
            statusCodes:
              - 404
       
      - id: customer_route
        uri: http://localhost:8083/
        predicates:
        - Path=/customer/**

---

spring:
  profiles: prod
  cloud:
    gateway:
      routes:
      - id: order_route
        uri: http://localhost:8084/
        predicates:
        - Path=/order/**
       
      - id: customer_route
        uri: http://localhost:8083/
        predicates:
        - Path=/customer/**